version: '3'
services:
  nginx:
    image: nginx:1.27.5
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=skaliburn
      - MONGO_INITDB_ROOT_PASSWORD=gdb485093lwu2
    volumes:
      - mongo-db:/data/db

  redis: 
    image: redis
volumes:
  mongo-db: