version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=skaliburn
      - MONGO_PASSWORD=gdb485093lwu2
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=skaliburn
      - MONGO_INITDB_ROOT_PASSWORD=gdb485093lwu2
      
